---
name: Bug report
description: >-
  Report a bug or an unexpected behavior to help us improve AUT
title: 'BUG: '
labels:
- bug
- triage

body:
- type: markdown
  attributes:
    value: >
      ## Thank you for helping us improve AUT!

      * First, please verify that your issue is not already reported using the
      [Issue search](https://github.com/splunk/addonfactory-ucc-test/search?q=is%3Aissue&type=issues).
- type: textarea
  attributes:
    label: Description
    description: A concise description of the bug.
  validations:
    required: true
- type: input
  attributes:
    label: What AUT version are you using?
    placeholder: For example splunk_add_on_ucc_modinput_test==1.0.0
  validations:
    required: true
- type: input
  attributes:
    label: Additional System Info
    placeholder: Python version, OS (Linux/Mac/Windows/WSL), etc.
  validations:
    required: true
