name: docs
on:
  push:
    branches:
      - "main"
      - "develop"
      - "release/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "release/**"
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.5.1
          pip install mkdocs mkdocs-material mkdocstrings-python
      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        run: mkdocs gh-deploy --force
      - name: Build Docs
        if: github.ref_name != 'main'
        run: mkdocs build
